package GUI;

import cardBase.*;
import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import gameTypes.highLow;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

public class gamePanel_highLow extends javax.swing.JPanel {
    
    highLow game = new highLow();
    int playedGame = 2;
    
    /**
     * Initializes the game view and makes restart button invisible
     */
    public gamePanel_highLow() {
        initComponents();
        restartButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardImage = new javax.swing.JLabel();
        text_Score = new javax.swing.JLabel();
        text_cardBe = new javax.swing.JLabel();
        lowerButton = new javax.swing.JButton();
        text_or = new javax.swing.JLabel();
        higherButton = new javax.swing.JButton();
        text_willTheNext = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        currentCard = new javax.swing.JLabel();
        restartButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(850, 550));
        setLayout(null);
        add(cardImage);
        cardImage.setBounds(450, 120, 130, 160);

        text_Score.setFont(new java.awt.Font("04b03", 0, 48)); // NOI18N
        text_Score.setText("Score:");
        add(text_Score);
        text_Score.setBounds(360, 460, 160, 40);

        text_cardBe.setFont(new java.awt.Font("04b03", 0, 24)); // NOI18N
        text_cardBe.setText("card be");
        add(text_cardBe);
        text_cardBe.setBounds(120, 380, 96, 24);

        lowerButton.setFont(new java.awt.Font("04b03", 0, 36)); // NOI18N
        lowerButton.setText("lower");
        lowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowerButtonActionPerformed(evt);
            }
        });
        add(lowerButton);
        lowerButton.setBounds(280, 340, 160, 80);

        text_or.setFont(new java.awt.Font("04b03", 0, 24)); // NOI18N
        text_or.setText("or");
        add(text_or);
        text_or.setBounds(480, 370, 27, 24);

        higherButton.setFont(new java.awt.Font("04b03", 0, 36)); // NOI18N
        higherButton.setText("higher");
        higherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                higherButtonActionPerformed(evt);
            }
        });
        add(higherButton);
        higherButton.setBounds(540, 340, 153, 80);

        text_willTheNext.setFont(new java.awt.Font("04b03", 0, 24)); // NOI18N
        text_willTheNext.setText("Will the next");
        add(text_willTheNext);
        text_willTheNext.setBounds(90, 350, 161, 24);

        score.setFont(new java.awt.Font("04b03", 0, 65)); // NOI18N
        score.setText("0");
        add(score);
        score.setBounds(530, 450, 70, 60);

        currentCard.setFont(new java.awt.Font("04b_19", 0, 18)); // NOI18N
        currentCard.setText("current card");
        add(currentCard);
        currentCard.setBounds(420, 300, 320, 30);

        restartButton.setFont(new java.awt.Font("04b03", 0, 36)); // NOI18N
        restartButton.setText("start again?");
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });
        add(restartButton);
        restartButton.setBounds(280, 340, 410, 80);
    }// </editor-fold>//GEN-END:initComponents

    private void lowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowerButtonActionPerformed
        Card card = game.getCurrentCard();        
        BufferedImage cardIMG = card.getCardImage();
        Image scaledCard = cardIMG.getScaledInstance( 90, 138,  java.awt.Image.SCALE_SMOOTH ) ;
        cardImage.setIcon(new ImageIcon(scaledCard));        
        
        currentCard.setText(game.getCurrentCard().toString() + " [" + game.getCurrentCard().getCardIntValue() + "]");
               
        playedGame = game.chooseLow();        
        
            if(playedGame == 0) {
                score.setText("---");
                cardIMG = card.getCardBackImage();
                scaledCard = cardIMG.getScaledInstance( 90, 138,  java.awt.Image.SCALE_SMOOTH ) ;
                cardImage.setIcon(new ImageIcon(scaledCard));             
                lowerButton.setVisible(false);
                higherButton.setVisible(false);
                text_or.setVisible(false);
                restartButton.setVisible(true);
                currentCard.setText("final score: " + game.getCurrentScore());
                game = new highLow();
            }
            else {
                score.setText(game.getCurrentScore() + "");
            }
    }//GEN-LAST:event_lowerButtonActionPerformed

    private void higherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_higherButtonActionPerformed
        Card card = game.getCurrentCard();        
        BufferedImage cardIMG = card.getCardImage();
        Image scaledCard = cardIMG.getScaledInstance( 90, 138,  java.awt.Image.SCALE_SMOOTH ) ;
        cardImage.setIcon(new ImageIcon(scaledCard));        
        
        currentCard.setText(game.getCurrentCard().toString() + " [" + game.getCurrentCard().getCardIntValue() + "]");
               
        playedGame = game.chooseHigh();
        
            if(playedGame == 0) {
                score.setText("---");
                cardIMG = card.getCardBackImage();
                scaledCard = cardIMG.getScaledInstance( 90, 138,  java.awt.Image.SCALE_SMOOTH ) ;
                cardImage.setIcon(new ImageIcon(scaledCard));             
                lowerButton.setVisible(false);
                higherButton.setVisible(false);
                text_or.setVisible(false);
                restartButton.setVisible(true);               
                currentCard.setText("final score: " + game.getCurrentScore());
                game = new highLow();
            }
            else {
                score.setText(game.getCurrentScore() + "");
            }
            
    }//GEN-LAST:event_higherButtonActionPerformed

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
                lowerButton.setVisible(true);
                higherButton.setVisible(true);
                text_or.setVisible(true);
                restartButton.setVisible(false);
                
                Card card = game.getCurrentCard();
                BufferedImage cardIMG = card.getCardImage();
                Image scaledCard = cardIMG.getScaledInstance( 90, 138,  java.awt.Image.SCALE_SMOOTH ) ;
                cardImage.setIcon(new ImageIcon(scaledCard));
                
                currentCard.setText(game.getCurrentCard().toString() + " [" + game.getCurrentCard().getCardIntValue() + "]");
                
                playedGame = 2;              
                game = new highLow();
    }//GEN-LAST:event_restartButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cardImage;
    private javax.swing.JLabel currentCard;
    private javax.swing.JButton higherButton;
    private javax.swing.JButton lowerButton;
    private javax.swing.JButton restartButton;
    private javax.swing.JLabel score;
    private javax.swing.JLabel text_Score;
    private javax.swing.JLabel text_cardBe;
    private javax.swing.JLabel text_or;
    private javax.swing.JLabel text_willTheNext;
    // End of variables declaration//GEN-END:variables
}
