package GUI;

import static GUI.MainMenuLayout.show_main_menu;
import cardBase.*;
import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import gameTypes.highLow;
import highScores.HighScoreManager;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

public class gamePanel_highLow extends javax.swing.JPanel {
    
    private highLow game = new highLow();
    private HighScoreManager scores = new HighScoreManager();
    private boolean playedGame;
        
    /**
     * Initializes the game view and makes restart button invisible
     */
    public gamePanel_highLow() {
        initComponents();
        Card card = game.getCurrentCard();
        BufferedImage cardIMG = card.getCardBackImage();
        Image scaledCard = cardIMG.getScaledInstance( 90, 138,  java.awt.Image.SCALE_SMOOTH ) ;
        cardImage.setIcon(new ImageIcon(scaledCard));
        lowerButton.setVisible      (false);
        higherButton.setVisible     (false);
        text_or.setVisible          (false);
        text_willTheNext.setVisible (false);
        text_cardBe.setVisible      (false);
        text_Score.setVisible       (false);
        score.setVisible            (false);
        score_popupJPanel.setVisible(false);
        score_popup_name.setVisible (false);
        score_popup_title.setVisible(false);
        finalScore.setVisible       (true);
        restartButton.setText       ("start playing!");
        restartButton.setVisible    (true);
        highscores_text.setVisible  (true);
        updateHighScoreList();
        highscores_list.setVisible  (true);    
    }
    
    private void updateHighScoreList() {
        highscores_list.setText("<html>" +  scores.getHighscoreString(1) + "<br><br>" + 
                                            scores.getHighscoreString(2) + "<br><br>" + 
                                            scores.getHighscoreString(3) + "<br><br>" + 
                                            scores.getHighscoreString(4) + "<br><br>" + 
                                            scores.getHighscoreString(5) + "<br><br>" + 
                                            scores.getHighscoreString(6) + "<br><br>" + 
                                            scores.getHighscoreString(7) + "<br><br>" + 
                                            scores.getHighscoreString(8) + "<br><br>" + 
                                            scores.getHighscoreString(9) + "<br><br>" + 
                                            scores.getHighscoreString(10) + "</html>" );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        score_popupJPanel = new javax.swing.JPanel();
        saveScoreJbutton = new javax.swing.JButton();
        namefield = new javax.swing.JTextField();
        score_popup_name = new javax.swing.JLabel();
        score_popup_title = new javax.swing.JLabel();
        cardImage = new javax.swing.JLabel();
        text_Score = new javax.swing.JLabel();
        text_cardBe = new javax.swing.JLabel();
        lowerButton = new javax.swing.JButton();
        text_or = new javax.swing.JLabel();
        higherButton = new javax.swing.JButton();
        text_willTheNext = new javax.swing.JLabel();
        finalScore = new javax.swing.JLabel();
        currentCard = new javax.swing.JLabel();
        restartButton = new javax.swing.JButton();
        score = new javax.swing.JLabel();
        backToMenu = new javax.swing.JButton();
        highscores_text = new javax.swing.JLabel();
        highscores_list = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(850, 550));
        setLayout(null);

        score_popupJPanel.setBackground(new java.awt.Color(0, 204, 0));
        score_popupJPanel.setLayout(null);

        saveScoreJbutton.setBackground(new java.awt.Color(0, 204, 102));
        saveScoreJbutton.setFont(new java.awt.Font("04b03", 0, 24)); // NOI18N
        saveScoreJbutton.setForeground(new java.awt.Color(255, 255, 255));
        saveScoreJbutton.setText("GO");
        saveScoreJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveScoreJbuttonActionPerformed(evt);
            }
        });
        score_popupJPanel.add(saveScoreJbutton);
        saveScoreJbutton.setBounds(150, 140, 80, 40);

        namefield.setFont(new java.awt.Font("04b03", 0, 24)); // NOI18N
        namefield.setToolTipText("");
        namefield.setName(""); // NOI18N
        namefield.setVerifyInputWhenFocusTarget(false);
        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        score_popupJPanel.add(namefield);
        namefield.setBounds(100, 70, 240, 50);

        score_popup_name.setFont(new java.awt.Font("04b03", 0, 30)); // NOI18N
        score_popup_name.setForeground(new java.awt.Color(255, 255, 255));
        score_popup_name.setText("name:");
        score_popupJPanel.add(score_popup_name);
        score_popup_name.setBounds(10, 80, 90, 30);

        score_popup_title.setFont(new java.awt.Font("04b03", 0, 36)); // NOI18N
        score_popup_title.setForeground(new java.awt.Color(255, 255, 255));
        score_popup_title.setText("NEW HIGHSCORE!");
        score_popupJPanel.add(score_popup_title);
        score_popup_title.setBounds(40, 10, 300, 40);

        add(score_popupJPanel);
        score_popupJPanel.setBounds(310, 140, 360, 190);
        add(cardImage);
        cardImage.setBounds(450, 120, 130, 160);

        text_Score.setFont(new java.awt.Font("04b03", 0, 48)); // NOI18N
        text_Score.setText("Score:");
        add(text_Score);
        text_Score.setBounds(360, 460, 160, 40);

        text_cardBe.setFont(new java.awt.Font("04b03", 0, 24)); // NOI18N
        text_cardBe.setText("card be");
        add(text_cardBe);
        text_cardBe.setBounds(120, 380, 96, 24);

        lowerButton.setFont(new java.awt.Font("04b03", 0, 36)); // NOI18N
        lowerButton.setText("lower");
        lowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowerButtonActionPerformed(evt);
            }
        });
        add(lowerButton);
        lowerButton.setBounds(280, 340, 160, 80);

        text_or.setFont(new java.awt.Font("04b03", 0, 24)); // NOI18N
        text_or.setText("or");
        add(text_or);
        text_or.setBounds(480, 370, 27, 24);

        higherButton.setFont(new java.awt.Font("04b03", 0, 36)); // NOI18N
        higherButton.setText("higher");
        higherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                higherButtonActionPerformed(evt);
            }
        });
        add(higherButton);
        higherButton.setBounds(540, 340, 153, 80);

        text_willTheNext.setFont(new java.awt.Font("04b03", 0, 24)); // NOI18N
        text_willTheNext.setText("Will the next");
        add(text_willTheNext);
        text_willTheNext.setBounds(90, 350, 161, 24);

        finalScore.setFont(new java.awt.Font("04b03", 0, 40)); // NOI18N
        finalScore.setToolTipText("");
        add(finalScore);
        finalScore.setBounds(330, 470, 360, 40);

        currentCard.setFont(new java.awt.Font("04b_19", 0, 18)); // NOI18N
        add(currentCard);
        currentCard.setBounds(400, 300, 320, 30);

        restartButton.setFont(new java.awt.Font("04b03", 0, 36)); // NOI18N
        restartButton.setText("start again?");
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });
        add(restartButton);
        restartButton.setBounds(280, 340, 410, 80);

        score.setFont(new java.awt.Font("04b03", 0, 65)); // NOI18N
        score.setText("0");
        add(score);
        score.setBounds(540, 450, 110, 60);

        backToMenu.setFont(new java.awt.Font("04b03", 1, 48)); // NOI18N
        backToMenu.setText("<-");
        backToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuActionPerformed(evt);
            }
        });
        add(backToMenu);
        backToMenu.setBounds(0, 0, 90, 40);

        highscores_text.setFont(new java.awt.Font("1st Sortie", 1, 48)); // NOI18N
        highscores_text.setText("TOP 10");
        add(highscores_text);
        highscores_text.setBounds(10, 60, 150, 50);

        highscores_list.setFont(new java.awt.Font("1st Sortie", 0, 24)); // NOI18N
        highscores_list.setText("rank. name - score");
        add(highscores_list);
        highscores_list.setBounds(10, 110, 360, 410);
    }// </editor-fold>//GEN-END:initComponents

    private void lowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowerButtonActionPerformed
        
        playedGame = game.chooseLow();
    
        if(playedGame == true) {
                Card card = game.getCurrentCard();
                BufferedImage cardIMG = card.getCardBackImage();
                Image scaledCard = cardIMG.getScaledInstance( 90, 138,  java.awt.Image.SCALE_SMOOTH ) ;
                cardImage.setIcon(new ImageIcon(scaledCard));
                lowerButton.setVisible      (false);
                higherButton.setVisible     (false);
                text_or.setVisible          (false);
                text_willTheNext.setVisible (false);
                text_cardBe.setVisible      (false);
                text_Score.setVisible       (false);
                score.setVisible            (false);
                finalScore.setVisible       (true);                              
                restartButton.setText("play again?");
                
                    if(scores.isHighScore(game.getCurrentScore())) {
                    cardIMG = card.getCardBackImage();
                    scaledCard = cardIMG.getScaledInstance( 90, 138,  java.awt.Image.SCALE_SMOOTH ) ;
                    cardImage.setIcon(new ImageIcon(scaledCard));
                    score_popupJPanel.setVisible(true);
                    score_popup_name.setVisible(true);
                    score_popup_title.setVisible(true);
                    saveScoreJbutton.setVisible (true);
                    score_popup_name.setVisible(true);
                    score_popup_title.setVisible(true);
                    namefield.setVisible        (true);                   
                } else {
                    restartButton.setVisible    (true);
                    highscores_text.setVisible  (true);
                    updateHighScoreList();
                    highscores_list.setVisible  (true);
                }              
                    finalScore.setText("final score: " + game.getCurrentScore());               
        } else {
                score.setText(game.getCurrentScore() + "");
            } 
        
        Card card = game.getCurrentCard();        
        BufferedImage cardIMG = card.getCardImage();
        Image scaledCard = cardIMG.getScaledInstance( 90, 138,  java.awt.Image.SCALE_SMOOTH ) ;
        cardImage.setIcon(new ImageIcon(scaledCard));
        currentCard.setText(game.getCurrentCard().toString() + " [" + game.getCurrentCard().getCardIntValue() + "]");                    
    }//GEN-LAST:event_lowerButtonActionPerformed

    private void higherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_higherButtonActionPerformed
        
        playedGame = game.chooseHigh();
    
        if(playedGame == true) {
                Card card = game.getCurrentCard();
                BufferedImage cardIMG = card.getCardBackImage();
                Image scaledCard = cardIMG.getScaledInstance( 90, 138,  java.awt.Image.SCALE_SMOOTH ) ;
                cardImage.setIcon(new ImageIcon(scaledCard));
                lowerButton.setVisible      (false);
                higherButton.setVisible     (false);
                text_or.setVisible          (false);
                text_willTheNext.setVisible (false);
                text_cardBe.setVisible      (false);
                text_Score.setVisible       (false);
                score.setVisible            (false);
                finalScore.setVisible       (true);                              
                restartButton.setText("play again?");
                
                if(scores.isHighScore(game.getCurrentScore())) {
                    cardIMG = card.getCardBackImage();
                    scaledCard = cardIMG.getScaledInstance( 90, 138,  java.awt.Image.SCALE_SMOOTH ) ;
                    cardImage.setIcon(new ImageIcon(scaledCard));
                    score_popupJPanel.setVisible(true);
                    score_popup_name.setVisible(true);
                    score_popup_title.setVisible(true);
                    saveScoreJbutton.setVisible (true);
                    score_popup_name.setVisible(true);
                    score_popup_title.setVisible(true);
                    namefield.setVisible        (true);                  
                } else {
                    restartButton.setVisible    (true);
                    highscores_text.setVisible  (true);
                    updateHighScoreList();
                    highscores_list.setVisible  (true);
                }              
                    finalScore.setText("final score: " + game.getCurrentScore());
                }
                else {
                    score.setText(game.getCurrentScore() + "");
                } 
        
        Card card = game.getCurrentCard();        
        BufferedImage cardIMG = card.getCardImage();
        Image scaledCard = cardIMG.getScaledInstance( 90, 138,  java.awt.Image.SCALE_SMOOTH ) ;
        cardImage.setIcon(new ImageIcon(scaledCard));
        currentCard.setText(game.getCurrentCard().toString() + " [" + game.getCurrentCard().getCardIntValue() + "]");    
        
    }//GEN-LAST:event_higherButtonActionPerformed

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
                lowerButton.setVisible      (true);
                higherButton.setVisible     (true);
                text_or.setVisible          (true);
                text_willTheNext.setVisible (true);
                text_cardBe.setVisible      (true);
                text_Score.setVisible       (true);
                score.setVisible            (true);
                finalScore.setVisible       (false);
                restartButton.setVisible    (false);
                highscores_text.setVisible  (false);
                highscores_list.setVisible  (false);
                playedGame = false;
                
                game = new highLow();
                Card card = game.getCurrentCard();
                BufferedImage cardIMG = card.getCardImage();
                Image scaledCard = cardIMG.getScaledInstance( 90, 138,  java.awt.Image.SCALE_SMOOTH ) ;
                cardImage.setIcon(new ImageIcon(scaledCard));
                
                currentCard.setText(game.getCurrentCard().toString() + " [" + game.getCurrentCard().getCardIntValue() + "]");
                score.setText(game.getCurrentScore() + "");
    }//GEN-LAST:event_restartButtonActionPerformed

    private void saveScoreJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveScoreJbuttonActionPerformed
        scores.addScore(namefield.getText(), game.getCurrentScore());
        score_popupJPanel.setVisible(false);
        saveScoreJbutton.setVisible (false);
        namefield.setVisible        (false);
        restartButton.setVisible    (true);
        highscores_text.setVisible  (true);
        updateHighScoreList();
        highscores_list.setVisible  (true);
        
        System.out.print(scores.getHighscoreString());
    }//GEN-LAST:event_saveScoreJbuttonActionPerformed

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        
    }//GEN-LAST:event_namefieldActionPerformed

    private void backToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuActionPerformed
        show_main_menu();
    }//GEN-LAST:event_backToMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMenu;
    private javax.swing.JLabel cardImage;
    private javax.swing.JLabel currentCard;
    private javax.swing.JLabel finalScore;
    private javax.swing.JButton higherButton;
    private javax.swing.JLabel highscores_list;
    private javax.swing.JLabel highscores_text;
    private javax.swing.JButton lowerButton;
    private javax.swing.JTextField namefield;
    private javax.swing.JButton restartButton;
    private javax.swing.JButton saveScoreJbutton;
    private javax.swing.JLabel score;
    private javax.swing.JPanel score_popupJPanel;
    private javax.swing.JLabel score_popup_name;
    private javax.swing.JLabel score_popup_title;
    private javax.swing.JLabel text_Score;
    private javax.swing.JLabel text_cardBe;
    private javax.swing.JLabel text_or;
    private javax.swing.JLabel text_willTheNext;
    // End of variables declaration//GEN-END:variables
}
